### ISSUE TITLE
Problems while trying to start the containers.

### ISSUE THREAD

**Issue by asnir** [qnib/docker-zkui#2]
I am trying to run the following command:

> docker-compose up -d

**The error:**
Creating dockerzkui_consul_1
ERROR: json: cannot unmarshal string into Go value of type []string

Am i missing something?

**Comment by ChristianKniep** [comment]
Could you please rename your `.docker/config`. I got the error when I updated to a newer version of docker and my config was not valid anymore.

```
➜  docker-zkui git:(master) docker-compose up -d                                                                                                                          git:(master|)
Creating dockerzkui_consul_1
Creating dockerzkui_zkui_1
Creating dockerzkui_zookeeper_1
➜  docker-zkui git:(master)
```
