### ISSUE TITLE
spin up zkui without zookeeper and consul

### ISSUE THREAD

**Issue by imrangit** [qnib/docker-zkui#3]
I would just like to spin up zkui and then have it point to the remote zookeeper server. How can i do that?

**Comment by ChristianKniep** [comment]
Hey there, just provide a list of ZK nodes with `ZKUI_ZK_SERVER` (e.g. `ZKUI_ZK_SERVER=zookeeperhost:2181`) and it will point there.
The magic is in the consul-template:  https://github.com/qnib/docker-zkui/blob/master/etc/consul-templates/zkui.conf.ctmpl#L3-L4

**Comment by imrangit** [comment]
HI Christian,

So this is what I have done. I build the image from your Dockerfile and this is how I am running it:

sudo docker run -d -p 9010:9010 -e SUPERVISOR_AUTOSTART_SRV=zkui -e ZKUI_ZK_SERVER=myzkinstance:2181 zkui

After that, it doesn’t respond on 9010 port. I only care about zkui, and i dont want to spin up consul or zookeepers in the container.

-Imran

**Comment by ChristianKniep** [comment]
You do not need to specify SUPERVISOR_AUTOSTART_SRV, it should work out of the box.
I'm on the run, so I won't have time to check it myself.
Please try `-p 9090:9090`, since that should be the port. 

Reply if you can not make it work, I will have a look tomorow and update the README to provide more details on that.

Thanks for reporting, I appreciate it!

**Comment by ChristianKniep** [comment]
Ah, maybe you are right with the AUTOSTART thingy... I'll have a look tomorrow...

**Comment by imrangit** [comment]
Hi Christian,

Any update to this?

-Imran

**Comment by ChristianKniep** [comment]
Hey @imrangit, sorry I am a bit swamped here. I will check it out as fast as I can.

**Comment by ChristianKniep** [comment]
Here we go, I checked the image and beefed it up a little. Please visit the README for instructions, it should work as expected now.
- https://github.com/qnib/docker-zkui/commit/ea25afc2cf6c2471b3e6ca1da76d1303f065fa77
- https://github.com/qnib/docker-zkui/commit/4aa51d75b00659b52cbd40146dd84d4f01bb5637
  If you encounter any issues or counterintuitiveness (I wonder if I spell this one right), please reopen.

Cheers and thanks for poking me on this, I really appreciate it!
